spring:
  application:
    name: authhandler
  datasource:
    url: jdbc:mysql://localhost:3306/invento_auth
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/tenant_id/v2.0
            user-name-attribute: name
        registration:
          azure-dev:
            provider: azure
            client-id: azure_app_client_id
            client-secret: azure_app_client_secret
            scope:
            - openid
            - email
            - profile